codecov:
  notify:
    require_ci_to_pass: yes
ignore:
  - "did_it_run/src/main.rs"
  - "did_it_run/src/notifications/desktop.rs"
coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 95
    patch:
      default:
        target: 95
    changes: no
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
