language: rust
sudo: required
rust:
  - stable
  - beta
cache: cargo
before_script:
  - ./tests/fixtures/tls/make-cert.sh
  - sudo ./tests/fixtures/tls/install-cert.sh
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo install --force --path did_it_run
  - ./run-test-scripts.sh
jobs:
  include:
    - stage: style and coverage
      rust: nightly
      cache: cargo
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      before_script:
        - ./tests/fixtures/tls/make-cert.sh
        - sudo ./tests/fixtures/tls/install-cert.sh
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo test --verbose --all --no-run
        - ./check-style.sh
      after_success:
        - ./.build-scripts/codecov.sh
