language: rust
sudo: required
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  # Fall back to an older nightly if the current version doesn't have rustfmt
  # and clippy
  - >
    rustup install nightly &&
    rustup component add rustfmt-preview --toolchain nightly &&
    rustup component add clippy-preview --toolchain nightly ||
      rustup install nightly-2019-02-26 &&
      rustup component add rustfmt-preview --toolchain nightly-2019-02-26 &&
      rustup component add clippy-preview --toolchain nightly-2019-02-26
script:
  - cargo build --verbose --all
  - ./test.sh
  - ./check-style.sh
after_success:
  - ./.build-scripts/codecov.sh
